/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */

export type GetConfigs200Data = {
  /** Nome do site WordPress */
  site_name?: string;
  /** Descrição do site WordPress */
  site_description?: string;
  /** URL do WhatsApp para contato */
  whatsapp_url?: string;
  /** ID do Google Analytics */
  google_analytics_id?: string;
  /** ID do Google Tag Manager */
  google_tag_manager_id?: string;
  /** URL do aplicativo frontend */
  frontend_app_url?: string;
  /** Usuário do GitHub */
  github_user?: string;
  /** Repositório do GitHub */
  github_repo?: string;
};
