/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetConfigs200Data } from './getConfigs200Data';

export type GetConfigs200 = {
  success?: boolean;
  data?: GetConfigs200Data;
};
