/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */

/**
 * Status do pagamento
 */
export type GetOrdersOrderIdPaymentStatus200Status = typeof GetOrdersOrderIdPaymentStatus200Status[keyof typeof GetOrdersOrderIdPaymentStatus200Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetOrdersOrderIdPaymentStatus200Status = {
  paid: 'paid',
  pending: 'pending',
} as const;
