/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrdersOrderIdPaymentStatus404Data } from './getOrdersOrderIdPaymentStatus404Data';

export type GetOrdersOrderIdPaymentStatus404 = {
  code?: string;
  message?: string;
  data?: GetOrdersOrderIdPaymentStatus404Data;
};
