/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */

export type GetOrdersBookDetails200Data = {
  /** ID do livro no WordPress */
  id?: number;
  /** Nome/título do livro */
  nome?: string;
  /** Preço do livro em reais (R$) */
  preco?: number;
};
