/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */

export type GetOrdersOrderIdPix200 = {
  message?: string;
  /** Imagem do QR Code PIX em base64 */
  qr_code_image?: string;
  /** Código PIX para copiar e colar */
  qr_code_copypaste?: string;
  /** Data de expiração do QR Code PIX */
  expiration_date?: string;
};
