/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrdersOrderIdPaymentStatus200Status } from './getOrdersOrderIdPaymentStatus200Status';

export type GetOrdersOrderIdPaymentStatus200 = {
  /** Mensagem descritiva do status */
  message?: string;
  /** Status do pagamento */
  status?: GetOrdersOrderIdPaymentStatus200Status;
};
