/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrdersOrderIdCheckCoupon404Data } from './getOrdersOrderIdCheckCoupon404Data';

export type GetOrdersOrderIdCheckCoupon404 = {
  code?: string;
  message?: string;
  data?: GetOrdersOrderIdCheckCoupon404Data;
};
