/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrdersOrderIdPix404Data } from './getOrdersOrderIdPix404Data';

export type GetOrdersOrderIdPix404 = {
  code?: string;
  message?: string;
  data?: GetOrdersOrderIdPix404Data;
};
