/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrdersBookDetails200Data } from './getOrdersBookDetails200Data';

export type GetOrdersBookDetails200 = {
  success?: boolean;
  data?: GetOrdersBookDetails200Data;
  message?: string;
};
