/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetOrdersCheckCoupon404Data } from './getOrdersCheckCoupon404Data';

export type GetOrdersCheckCoupon404 = {
  code?: string;
  message?: string;
  data?: GetOrdersCheckCoupon404Data;
};
