/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetPostSlug200Data } from './getPostSlug200Data';

export type GetPostSlug200 = {
  success?: boolean;
  data?: GetPostSlug200Data;
};
