/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetPostSlugs401Data } from './getPostSlugs401Data';

export type GetPostSlugs401 = {
  code?: string;
  message?: string;
  data?: GetPostSlugs401Data;
};
