/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { GetPostSlug400Data } from './getPostSlug400Data';

export type GetPostSlug400 = {
  code?: string;
  message?: string;
  data?: GetPostSlug400Data;
};
