/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */

export type GetWebhookCheckFaceswap200 = {
  message?: string;
  /** Número de pedidos finalizados (status atualizado para created_assets_illustration) */
  processed?: number;
  /** Número total de pedidos verificados */
  total?: number;
  /** Lista de erros encontrados (vazia em caso de sucesso) */
  errors?: string[];
};
