/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */

export type GetWebhookDeliverPdf500 = {
  message?: string;
  /** Número de pedidos entregues com sucesso */
  processed?: number;
  /** Número total de pedidos encontrados */
  total?: number;
  /** Lista detalhada de erros encontrados */
  errors?: string[];
};
