/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */

export type GetWebhookDeliverPdf200 = {
  message?: string;
  /** Número de pedidos que foram entregues com sucesso */
  processed?: number;
  /** Número total de pedidos encontrados com status 'ready_for_delivery' */
  total?: number;
  /** Lista de erros encontrados (vazia em caso de sucesso) */
  errors?: string[];
};
