/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */

export * from './getConfigs200';
export * from './getConfigs200Data';
export * from './getConfigs401';
export * from './getConfigs401Data';
export * from './getPostSlug200';
export * from './getPostSlug200Data';
export * from './getPostSlug400';
export * from './getPostSlug400Data';
export * from './getPostSlug401';
export * from './getPostSlug401Data';
export * from './getPostSlug404';
export * from './getPostSlug404Data';
export * from './getPostSlugs200';
export * from './getPostSlugs200DataItem';
export * from './getPostSlugs401';
export * from './getPostSlugs401Data';
export * from './getPostSlugsParams';
export * from './postContactFormSubmit200';
export * from './postContactFormSubmit400';
export * from './postContactFormSubmit400OneOf';
export * from './postContactFormSubmit400OneOfData';
export * from './postContactFormSubmit400OneOfFive';
export * from './postContactFormSubmit400OneOfFiveData';
export * from './postContactFormSubmit400OneOfThree';
export * from './postContactFormSubmit400OneOfThreeData';
export * from './postContactFormSubmit401';
export * from './postContactFormSubmit401Data';
export * from './postContactFormSubmit500';
export * from './postContactFormSubmit500Data';
export * from './postContactFormSubmitBody';
export * from './postOrders201';
export * from './postOrders201Data';
export * from './postOrders400';
export * from './postOrders400OneOf';
export * from './postOrders400OneOfData';
export * from './postOrders400OneOfThree';
export * from './postOrders400OneOfThreeData';
export * from './postOrders401';
export * from './postOrders401Data';
export * from './postOrders500';
export * from './postOrders500Data';
export * from './postOrdersBody';
export * from './postOrdersBodyChildGender';
export * from './postOrdersBodySkinTone';
export * from './taxonomyTerm';