/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */

/**
 * Gênero da criança
 */
export type PostOrdersBodyChildGender = typeof PostOrdersBodyChildGender[keyof typeof PostOrdersBodyChildGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostOrdersBodyChildGender = {
  menino: 'menino',
  menina: 'menina',
} as const;
