/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { PostOrdersBodyChildGender } from './postOrdersBodyChildGender';
import type { PostOrdersBodySkinTone } from './postOrdersBodySkinTone';

export type PostOrdersBody = {
  /** Nome da criança */
  childName: string;
  /**
   * Idade da criança (1-18 anos)
   * @minimum 1
   * @maximum 18
   */
  childAge: number;
  /** Gênero da criança */
  childGender: PostOrdersBodyChildGender;
  /** Tom de pele da criança */
  skinTone: PostOrdersBodySkinTone;
  /** Nome do responsável */
  parentName: string;
  /** E-mail do responsável */
  email: string;
  /**
   * Telefone do responsável (formato: (99) 99999-9999)
   * @pattern ^\(\d{2}\)\s\d{5}-\d{4}$
   */
  phone: string;
  /** Foto do rosto da criança. Formatos: JPG, JPEG, PNG. Tamanho máximo: 5MB */
  photo: Blob;
};
