/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { PostWebhookPaymentConfirmBodyEvent } from './postWebhookPaymentConfirmBodyEvent';
import type { PostWebhookPaymentConfirmBodyPayment } from './postWebhookPaymentConfirmBodyPayment';

export type PostWebhookPaymentConfirmBody = {
  /** ID do evento */
  id?: string;
  /** Tipo do evento */
  event: PostWebhookPaymentConfirmBodyEvent;
  /** Data de criação do evento */
  dateCreated?: string;
  payment: PostWebhookPaymentConfirmBodyPayment;
};
