/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { PostContactFormSubmit400OneOf } from './postContactFormSubmit400OneOf';
import type { PostContactFormSubmit400OneOfThree } from './postContactFormSubmit400OneOfThree';
import type { PostContactFormSubmit400OneOfFive } from './postContactFormSubmit400OneOfFive';

export type PostContactFormSubmit400 = PostContactFormSubmit400OneOf | PostContactFormSubmit400OneOfThree | PostContactFormSubmit400OneOfFive;
