/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { PostContactFormSubmit400OneOfData } from './postContactFormSubmit400OneOfData';

export type PostContactFormSubmit400OneOf = {
  code?: string;
  message?: string;
  data?: PostContactFormSubmit400OneOfData;
};
