/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */

/**
 * Tom de pele da criança
 */
export type PostOrdersBodySkinTone = typeof PostOrdersBodySkinTone[keyof typeof PostOrdersBodySkinTone];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostOrdersBodySkinTone = {
  light: 'light',
  dark: 'dark',
} as const;
