/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */

/**
 * Tipo do evento
 */
export type PostWebhookPaymentConfirmBodyEvent = typeof PostWebhookPaymentConfirmBodyEvent[keyof typeof PostWebhookPaymentConfirmBodyEvent];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostWebhookPaymentConfirmBodyEvent = {
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
} as const;
