/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { PostOrders201Data } from './postOrders201Data';

export type PostOrders201 = {
  success?: boolean;
  message?: string;
  data?: PostOrders201Data;
};
