/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { PostOrders201AppliedCoupon } from './postOrders201AppliedCoupon';

export type PostOrders201 = {
  message?: string;
  order_id?: number;
  status?: string;
  /** Cupom aplicado no pedido, se informado */
  applied_coupon?: PostOrders201AppliedCoupon;
};
