/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */
import type { PostContactFormSubmit500Data } from './postContactFormSubmit500Data';

export type PostContactFormSubmit500 = {
  code?: string;
  message?: string;
  data?: PostContactFormSubmit500Data;
};
