/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */

export type PostWebhookPaymentConfirmBodyPayment = {
  /** ID da transação de pagamento */
  id: string;
  /** ID do pedido no WordPress */
  externalReference: string;
  /** Data do pagamento */
  paymentDate: string;
  /** Valor do pagamento */
  value: number;
};
