/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * TrinityKitWP API
 * API para gerenciamento de posts, pedidos personalizados e formulários de contato no WordPress
 * OpenAPI spec version: 1.0.0
 */

export interface TaxonomyTerm {
  /** ID do termo */
  id?: number;
  /** Nome do termo */
  name?: string;
  /** Slug do termo */
  slug?: string;
  /** Termos filhos */
  children?: TaxonomyTerm[];
}
